//created on: 7 May 2020


agenda-group "employmentTest"

rule "If there are not possible professions, find and insert them - employmentTest"
	no-loop
	lock-on-active
    when
    	$criteriums : Criteriums(personality == false, preferences==false, payment == false, employment == true)
    	$profession : Profession($employmentScore : employmentScore, $name : name)
    then
    	 System.out.println("Possible profession inserted "+$name);
    	 PossibleProfession possibleProfession = new PossibleProfession($profession);
    	 possibleProfession.increaseScore($employmentScore);
 	  	 insert(possibleProfession);
 	  	 delete($profession);
 	  	 
end

rule "If there are possible professions inserted, caluculate influence of employment"
    no-loop
	lock-on-active
    when
    
        $possibleProfession : PossibleProfession($employmentScore : profession.employmentScore, $name : profession.name)
    then
    
    	System.out.println("Score increase-employment "+$name);
        $possibleProfession.increaseScore($employmentScore);

end

