//created on: 7 May 2020


rule "If there are not possible professions, find and insert them - employmentTest"
	agenda-group "employmentTest"
	no-loop
	lock-on-active
    when
    	$criteriums : Criteriums(personality == false, preferences==false, payment == false, employment == true)
    	$profession : Profession($employment : employment, $name : name)
    then
    	 System.out.println("Possible profession inserted "+$name);
    	 PossibleProfession possibleProfession = new PossibleProfession($profession);
    	 possibleProfession.increaseScore((double) $employment/100);
 	  	 insert(possibleProfession);
 	  	 delete($profession);
 	  	 
end

rule "If there are possible professions inserted, caluculate influence of employment"
    agenda-group "employmentTest"
    no-loop
	lock-on-active
    when
    	$l : List( size > 0) from collect (PossibleProfession())
    
        $possibleProfession : PossibleProfession($employment : profession.employment, $name : profession.name)
    then
    
    	System.out.println("Score increase-employment "+$name);
        $possibleProfession.increaseScore((double) $employment/100);

end
