//created on: 5 Jun 2020
package events

import com.sbnz.career.adviser.model.*;
import com.sbnz.career.adviser.entity.*;
import com.sbnz.career.adviser.events.*;

agenda-group "loginEvents"


rule "More than 3 logging in unsuccessfully in 1 minutes from one user"
	
    when
        $e1: LoginEvent($userId: user.id, $user : user)
        Number(intValue >= 3) from accumulate(
            $e2: LoginEvent($successfull : successfull, $thisUser : user,
                this != $e1, 
                $successfull == false,
                $thisUser.id == $userId)
                over window:time(1m), count($e2)
            )
    then
    	System.out.println("Maximum number of atempts reached");
    	$user.setAllowed(false);     
end
 





rule "No suspicious login event, successfull login"
	
	when
        $e1: LoginEvent( $user: user, successfull==true)
        Number(intValue < 3 ) from accumulate(
			$l: LoginEvent(user.id == $user.id, successfull == false)
			over window:time(1m), count($l)
		)
       
		
	then
		$user.setAllowed(true);
		System.out.println("Allowed to login.");
		
end

