//created on: 9 May 2020
import com.sbnz.career.adviser.model.*;

/*
agenda-group "matchingTest"

//declare any global variables here
query returnMatchingTraits (List $matching, List $traitsTarget, Set $professionTraits)
	$matching:= List() 
				from accumulate( 
					$t : Trait( $target: getTarget(), $target memberOf $traitsTarget)
					from $professionTraits,
					collectList($t)
				)
end

query returnMatchingPreferences (List $matchingPreferences, List $prefTarget, Set $professionPref)
	$matchingPreferences:= List() 
				from accumulate( 
					$a : Preference($id: getId(), $id memberOf $prefTarget)
					from $professionPref,
					collectList($a)
				)
end

rule "Calculating number of matching traits"
	no-loop
	lock-on-active
    when
		$traitsList : List()
		$matching : Matching($matchTraits : traits)
		$profession : Profession($name : name, $profTraits : traits)
		
		$traitsTarget: List() from accumulate (
			$trait: Trait($target : target) from $traitsList,
			collectList($target)
		)
		returnMatchingTraits($matchingTraits, $traitsTarget, $profTraits;);   
    then
    	for (Object o : $matchingTraits){
    		Trait trait = (Trait) o;
    		$matchTraits.add(trait);
    	}
	     System.out.println("Found matching: " + $matchTraits.size());
	     System.out.println("Traits size list: "+$traitsList.size());
	     System.out.println("Prof traits list size: "+$profTraits.size());
	 	 
end

rule "Calculating number of matching preferences"
	no-loop
	lock-on-active
	when
		$matching : Matching($matchPref : preferences)
		$prefQuestResultList : List( size > 0) from collect (PreferenceQuestionResult())
		$prefResult: List() from accumulate (
			$pref: PreferenceQuestionResult(isChecked == true, $activityId : activity.getId()) from $prefQuestResultList,
			collectList($activityId)
		)
	 	$profession : Profession($name : name, $preferences : getActivities())
	 	returnMatchingPreferences($matchingPreferences, $prefResult, $preferences;);   
	then
	
		System.out.println("Everything satisfied "+$matchingPreferences.size());
		for (Object o : $matchingPreferences){
    		Preference activity = (Preference) o;
    		$matchPref.add(activity);
    	}
    	System.out.println("Found matching: " + $matchPref.size());
end


*/

