package rules

import com.sbnz.career.adviser.model.*;
import com.sbnz.career.adviser.entity.*;
import com.sbnz.career.adviser.events.*;

agenda-group "newProfessionTest"

rule "More than 1 attempt for redoing profession test in 1m"
    when
    	$e1: NewProfessionTestEvent($userId: user.id, $user : user)
    	Number(intValue >= 3) from accumulate(
            $e2: NewProfessionTestEvent($thisUser : user,
                this != $e1, 
                $thisUser.id == $userId)
                over window:time(2m), count($e2)
            )
           
    	 
    then
    	System.out.println("Maximum number of tests in two minutes reached.");
    	$user.setNewProfTest(false);   
end

rule "Allowed to do new profession test"
	when
        $e1: NewProfessionTestEvent( $user: user)
        Number(intValue < 3 ) from accumulate(
			$l: NewProfessionTestEvent(user.id == $user.id)
			over window:time(2m), count($l)
		)
	then
		$user.setNewProfTest(true);   
		System.out.println("Allowed to to new profession test.");
		
end