//created on: 6 Jun 2020
package rules

import com.sbnz.career.adviser.model.*;
import com.sbnz.career.adviser.entity.*;
import com.sbnz.career.adviser.events.*;

agenda-group "newPersonalityTest"






rule "More than 1 attempt for redoing personality test in 1m"
    when
    	$e1: NewPersonalityTestEvent($userId: user.id, $user : user)
    	Number(intValue >= 3) from accumulate(
            $e2: NewPersonalityTestEvent($thisUser : user,
                this != $e1, 
                $thisUser.id == $userId)
                over window:time(2m), count($e2)
            )
           
    	 
    then
    	System.out.println("Maximum number of tests in two minutes reached.");
    	$user.setNewPersTest(false);   
end

rule "Allowed to do new personality test"
	when
        $e1: NewPersonalityTestEvent( $user: user)
        Number(intValue < 3 ) from accumulate(
			$l: NewPersonalityTestEvent(user.id == $user.id)
			over window:time(2m), count($l)
		)
	then
		$user.setNewPersTest(true);   
		System.out.println("Allowed to to new personality test.");
		
end


