


import com.sbnz.career.adviser.model.*;
import java.util.List;

/*
rule "Traits result"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target)
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {increment($target);}
       System.out.println("Univerasl increment called");
end

*/


rule "Traits result - target extroverted, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "extraverted")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementExtraverted();}
       System.out.println("Target extraverted, isChecked == true");
end

rule "Traits result - target extroverted, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "extraverted")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementIntroverted();}
       System.out.println("Target extraverted, isChecked == false");
end

rule "Traits result - target introverted, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "introverted")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementIntroverted();}
       System.out.println("Target introverted, isChecked == true");
end

rule "Traits result - target introverted, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "introverted")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementExtraverted();}
       System.out.println("Target introverted, isChecked == false");
end



rule "Traits result - target assertive, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "assertive")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementAssertive();}
       System.out.println("Target assertive, isChecked == true");
end

rule "Traits result - target assertive, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "assertive")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementTurbulent();}
       System.out.println("Target assertive, isChecked == false");
end

rule "Traits result - target turbulent, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "turbulent")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementTurbulent();}
       System.out.println("Target turbulent, isChecked == true");
end

rule "Traits result - target turbulent, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "turbulent")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementAssertive();}
       System.out.println("Target turbulent, isChecked == false");
end



rule "Traits result - target thinking, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "thinking")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementThinking();}
       System.out.println("Target thinking, isChecked == true");
end

rule "Traits result - target thinking, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "thinking")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementFeeling();}
       System.out.println("Target thinking, isChecked == false");
end

rule "Traits result - target feeling, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "feeling")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementFeeling();}
       System.out.println("Target feeling, isChecked == true");
end

rule "Traits result - target feeling, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "feeling")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementThinking();}
       System.out.println("Target feeling, isChecked == false");
end

rule "Traits result - target realist, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "realist")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementRealist();}
       System.out.println("Target realist, isChecked == true");
end

rule "Traits result - target realist, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "realist")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementVisionary();}
       System.out.println("Target realist, isChecked == false");
end

rule "Traits result - target visionary, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "visionary")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementVisionary();}
       System.out.println("Target visionary, isChecked == true");
end

rule "Traits result - target visionary, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "visionary")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementRealist();}
       System.out.println("Target visionary, isChecked == false");
end

rule "Traits result - target judging, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "judging")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementJudging();}
       System.out.println("Target judging, isChecked == true");
end

rule "Traits result - target judging, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "judging")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementProspecting();}
       System.out.println("Target judging, isChecked == false");
end

rule "Traits result - target prospecting, isChecked == true"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == true, $target == "prospecting")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementProspecting();}
       System.out.println("Target prospecting, isChecked == true");
end

rule "Traits result - target prospecting, isChecked == false"
	agenda-group "personalityTest"
	no-loop
	lock-on-active
    when
        $traitQuestionResult: TraitQuestionResult($target : traitQuestion.trait.target, isChecked == false, $target == "prospecting")
        $traitsResult : TraitsResult()
    then
       modify($traitsResult) {incrementJudging();}
       System.out.println("Target prospecting, isChecked == false");
end





rule "Creating mind trait-extraverted"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($extraverted: extraverted, $introverted: introverted, $extraverted >= $introverted)
	then
		Trait trait = new Trait("mind", "extraverted");
		insert(trait);
		System.out.println("Extroverted inserted");
	
end

rule "Creating mind trait-introverted"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($extraverted: extraverted, $introverted: introverted, $extraverted < $introverted)
	then
		Trait trait = new Trait("mind", "introverted");
		insert(trait);
		System.out.println("Introverted inserted");
	
end

rule "Creating mind identity-assertive"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($assertive: assertive, $turbulent: turbulent, $assertive >= $turbulent)
	then
		Trait trait = new Trait("identity", "assertive");
		insert(trait);
		System.out.println("Assertive inserted");
end

rule "Creating mind identity-turbulent"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($assertive: assertive, $turbulent: turbulent, $assertive < $turbulent)
	then
		Trait trait = new Trait("identity", "turbulent");
		insert(trait);
		System.out.println("Turbulent inserted");
end

rule "Creating mind nature-thinking"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($thinking: thinking, $feeling: feeling, $thinking >= $feeling)
	then
		Trait trait = new Trait("nature", "thinking");
		insert(trait);
		System.out.println("Thinking inserted");
end

rule "Creating mind nature-feeling"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($thinking: thinking, $feeling: feeling, $thinking < $feeling)
	then
		Trait trait = new Trait("nature", "feeling");
		insert(trait);
		System.out.println("Feeling inserted");
end

rule "Creating mind energy-realist"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($realist: realist, $visionary: visionary, $realist >= $visionary)
	then
		Trait trait = new Trait("energy", "realist");
		insert(trait);
		System.out.println("Realist inserted");
end

rule "Creating mind energy-visionary"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($realist: realist, $visionary: visionary, $realist < $visionary)
	then
		Trait trait = new Trait("energy", "visionary");
		insert(trait);
		System.out.println("Visionary inserted");
end


rule "Creating mind tactics-judging"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($judging: judging, $prospecting: prospecting, $judging >= $prospecting)
	then
		Trait trait = new Trait("tactics", "judging");
		insert(trait);
		System.out.println("Judging inserted");
		
		
end

rule "Creating mind tactics-prospecting"
	agenda-group "personalityTest"
	salience -100
	no-loop
	when
		$traitsResult : TraitsResult($judging: judging, $prospecting: prospecting, $judging < $prospecting)
		
	then
		Trait trait = new Trait("tactics", "prospecting");
		insert(trait);
		System.out.println("Prospecting inserted");
		System.out.println($judging);
		System.out.println($prospecting);
end

rule "Grouping traits"
	agenda-group "personalityTest"
	salience -200
	when $list: List() from collect(Trait())
	then
	
	
		insert($list);
		System.out.println("Number of traits found: " + $list.size());
end
		
	
