//created on: 8 Jun 2020
package rules
import com.sbnz.career.adviser.model.*;
import com.sbnz.career.adviser.entity.*;
import com.sbnz.career.adviser.events.*;
import java.util.List;

agenda-group "report"


rule "Test done"
    when
        
        $td : TestDoneEvent() 
        over window:time(24h)
       
    then
    	System.out.println("First rule");
        insert(new Counter());
        delete($td);
       
        
end

rule "Increase in reports"
	when
		$testsInADay: TestsDoneInDay()
		$c : Counter()
	then
		System.out.println("Second rule");
		$testsInADay.increase();
		delete($c);
end
	
		
